# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "rose-pine"

# Palette definitions
[palettes.rose-pine]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
# highlight low = "#2
# highlight med = "#403d52"
# highlight high = "#524f67"

format = """
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$lua\n\
$character\
"""
# Starship modules
[character]
success_symbol = "[ ❯](iris)"
error_symbol = "[ ❯](love)"
vimcmd_symbol = "[ ❮](subtle)" # For use with zsh-vi-mode

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "󰜥  [](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[ ](bold fg:cyan)"

[fill]
style = "fg:overlay"
symbol = " "

[git_status]
disabled = false
style = "fg:love"
format = '(fg:overlay)([$all_status$ahead_behind]($style))(fg:overlay) '
up_to_date = '[✓](fg:iris)'
untracked = '[?\($count\)](fg:gold)'
stashed = '[\$](fg:iris)'
modified = '[!\($count\)](fg:gold)'
renamed = '[»\($count\)]fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](fg:gold)'
ahead = '[⇡\(${count}\)](fg:foam)'
diverged = '⇕[\[](fg:iris)[⇡\(${ahead_count}\)](fg:foam)[⇣\(${behind_count}\)](fg:rose)[\]](fg:iris)'
behind = '[⇣\(${count}\)](fg:rose)'

[directory]
format = "[$path ]($style)"
style = "bold fg:pine"
read_only = "  "
truncation_length = 6
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

# [cmd_duration]
# min_time = 0
# format = '[](bold fg:gold)[󰪢 $duration](bold bg:gold fg:black)[](bold fg:gold)'
