[pyprland]
plugins = [
  "scratchpads",
]


[scratchpads.term]
animation = "fromTop"
command = "wezterm start --class 'wezterm-dropterm'"
class = "wezterm-dropterm"
size = "65% 35%"
max_size = "1920px 100%"
offset = 700
lazy = true
margin = 52

# [scratchpads.clock]
# animation = "fromRight"
# command = "wezterm start --class 'wezterm-clock' peaclock"
# class = "wezterm-clock"
# size = "380px 275px"
# position = "1520px 403px"
# lazy = true
# max_size = "1920px 100%"

[scratchpads.yazi]
animation = "fromRight"
command = "wezterm start --class 'wezterm-yazi' -e yazi"
class = "wezterm-yazi"
size = "65% 60%"
max_size = "1920px 100%"
position = "336px 216px"
lazy = true
margin = 340

[scratchpads.spotify]
animation = "fromLeft"
command = "spotify"
class = "spotify"
match_by = "class"
size = "90% 88%"
max_size = "1920px 100%"
lazy = true
margin = 110

# [scratchpads.obsidian]
# animation = "fromBottom"
# command = "obsidian"
# class = "obsidian"
# match_by = "class"
# size = "65% 620px"
# max_size = "1920px 100%"
# lazy = true
# margin = 20
